export const DBConstants = {
  CREATED_BY: "created_by",
  IS_DELETED: "is_deleted",
  PHONE_NUMBER: "phone_number",
  EMAIL: "email",
  IS_ONBOARDING_COMPLETED: "is_onboarding_completed",
  PROFILE_PICTURE_URL: "profile_picture_url",
  HIRING_MANAGER: "HIRING_MANAGER",
  LOGIN_TYPE: "login_type",
  JS_ID: "js_id",
  HM_ID: "hm_id",
  JOB_ID: "job_id",
  MY_MEETING: "My Meeting",
  OUR_SHOWCASE: "Our Showcase",
  MY_SHOWCASE: "My Showcase",
  FLAIRCARD: "Flaircard",
  SNOWCARD: "Snowcard",
  USER_TYPE: "user_type",
  UPDATED_AT: "updated_at",
  CREATED_AT: "created_at",
  IS_JS_SEEN: "is_js_seen",
  IS_HM_SEEN: "is_hm_seen",
  ID: "id",
  FIRST_NAME: "first_name",
  LAST_NAME: "last_name",
  COMPANY: "company",
  DESCRIPTION: "description",
  TITLE: "title",
  MAIL_TO: "notify@snowflair.com",
};
